INSTALLDIR = /usr/local/bin

install:
	install -m 0755 musicdl ${DESTDIR}${INSTALLDIR} 
	install -m 0755 bookdl ${DESTDIR}${INSTALLDIR} 
	install -m 0755 limedl ${DESTDIR}${INSTALLDIR} 
	install -m 0755 walldl ${DESTDIR}${INSTALLDIR} 
	install -m 0755 notflix ${DESTDIR}${INSTALLDIR} 

.PHONY: install
