#!/bin/sh

# Prints the screen brightness
# Depends on:
# Miguel Neto (11/2024)

read -r actual_brightness </sys/class/backlight/intel_backlight/actual_brightness
read -r max_brightness </sys/class/backlight/intel_backlight/max_brightness
backlight="light: $((actual_brightness*100/max_brightness))%"

echo "$backlight"
