#!/bin/sh

# Prints the battery status
# Depends on:
# Miguel Neto (11/2024) 

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	case "$(cat "$battery/status" 2>&1)" in
		"Full") status="[full]" ;;
		"Discharging") status="x" ;;
		"Charging") status="[charging]" ;;
		"Not charging") status="x" ;;
		"Unknown") status="?" ;;
		*) exit 1 ;;
	esac
	capacity="$(cat "$battery/capacity" 2>&1)"
	# Will make a warn variable if discharging and low
	[ "$status" = "[discharging]" ] && [ "$capacity" -le 25 ] && warn="!"
	# Prints the info
	printf "%s %s%d%%" "$status" "$warn" "$capacity"; unset warn
done && printf "\\n"

