INSTALLDIR = /usr/local/bin

all: install

install:
	install -m 0755 vol ${DESTDIR}${INSTALLDIR} 
	install -m 0755 datefmt ${DESTDIR}${INSTALLDIR} 
	install -m 0755 battery ${DESTDIR}${INSTALLDIR} 

.PHONY: all install
