INSTALLDIR = /usr/local/bin

install:
	install -m 0755 vol ${DESTDIR}${INSTALLDIR}
	install -m 0755 datefmt ${DESTDIR}${INSTALLDIR}
	install -m 0755 battery ${DESTDIR}${INSTALLDIR}
	install -m 0755 backl ${DESTDIR}${INSTALLDIR}

.PHONY: install
