INSTALLDIR = /usr/local/bin

install:
	install -m 0755 extract ${DESTDIR}${INSTALLDIR} 
	install -m 0755 wificli ${DESTDIR}${INSTALLDIR} 
	install -m 0755 shup ${DESTDIR}${INSTALLDIR} 
	install -m 0755 upl ${DESTDIR}${INSTALLDIR} 
	install -m 0755 slowverb ${DESTDIR}${INSTALLDIR} 
	install -m 0755 setbg ${DESTDIR}${INSTALLDIR} 
	install -m 0755 linkhandler ${DESTDIR}${INSTALLDIR} 
	install -m 0755 opout ${DESTDIR}${INSTALLDIR} 
	install -m 0755 dmenuhandler ${DESTDIR}${INSTALLDIR} 
	install -m 0755 compiler ${DESTDIR}${INSTALLDIR} 

.PHONY: install
