#!/bin/bash

OPTSTRING=":cl"

while getopts ${OPTSTRING} opt; do
  case ${opt} in
    c)
      qemu-img create -f qcow2 $2.qcow2 20G
      ;;
    l)
      qemu-system-x86_64 -enable-kvm -drive file=$2 -cdrom $3 -m 2048
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done
