#!/bin/sh

# Connect to wifi in a prompt-fashioned way. 
# Depends on: networkmanager, dmenu
# Miguel Neto (11/2024)

bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | dmenu -p "Select wifi:" -l 20 | cut -d' ' -f1)
pass=$(echo "" | dmenu -p "Enter password:")
nmcli device wifi connect $bssid password $pass
